data:
  cifar_path: "../cifar-10-python"
  seed: 42

model:
  pretrained: true
  embedding_dim: 128

training:
  batch_size: 64
  learning_rate: 0.0005
  epochs: 5
  margin: 0.5
  koleo_loss_coeff: 0.5  # Set to a float value (e.g., 0.5) to enable KoLeo loss
  print_freq: 30

kfold:
  n_splits: 5
  shuffle: true

saving:
  save_weights: false
  save_every_n_epochs: 1

normalization:
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2470, 0.2435, 0.2616]

label_names: ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

ellipse_coverage: 0.50
